// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BikeStores.API.Infrastructure.Dtos
{
    public class BrandDto
    {
        public BrandDto()
        {            
        }

        public int BrandId { get; set; }
        public string BrandName { get; set; }
    }
}