// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using Net5.ChatRoom.Infrastructure.Data.Context.Configurations;
using Net5.ChatRoom.Infrastructure.Data.Entities;
using System;
#nullable disable

#nullable disable

namespace Net5.ChatRoom.Infrastructure.Data.Context
{
    public partial class ChatRoomContext : DbContext
    {
        public ChatRoomContext()
        {
        }

        public ChatRoomContext(DbContextOptions<ChatRoomContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Chat> Chats { get; set; }
        public virtual DbSet<Room> Rooms { get; set; }
        public virtual DbSet<RoomUser> RoomUsers { get; set; }
        public virtual DbSet<User> Users { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS");

            modelBuilder.ApplyConfiguration(new Configurations.ChatConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.RoomConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.RoomUserConfiguration());
            modelBuilder.ApplyConfiguration(new Configurations.UserConfiguration());
            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}
