// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BikeStores.API.Infrastructure.Dtos
{
    public class CategoryDto
    {
        public CategoryDto()
        {            
        }

        public int CategoryId { get; set; }
        public string CategoryName { get; set; }

    }
}