// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using BikeStores.API.Infrastructure.Data.Contexts;
using BikeStores.API.Infrastructure.Data.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace BikeStores.API.Infrastructure.Data.Contexts.Configurations
{
    public partial class BrandConfiguration : IEntityTypeConfiguration<Brand>
    {
        public void Configure(EntityTypeBuilder<Brand> entity)
        {
            entity.ToTable("brands", "production");

            entity.Property(e => e.BrandId).HasColumnName("brand_id");

            entity.Property(e => e.BrandName)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("brand_name");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Brand> entity);
    }
}
