// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Net5.ChatRoom.Infrastructure.Data.Entities
{
    public partial class User
    {
        public User()
        {
            Chats = new HashSet<Chat>();
            RoomUsers = new HashSet<RoomUser>();
        }

        public int UserId { get; set; }
        public string Password { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public DateTimeOffset? DateOfBirth { get; set; }
        public int Sex { get; set; }

        public virtual ICollection<Chat> Chats { get; set; }
        public virtual ICollection<RoomUser> RoomUsers { get; set; }
    }
}