// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Net5.ChatRoom.Infrastructure.Data.Entities
{
    public partial class RoomUser
    {
        public int RoomUserId { get; set; }
        public int RoomId { get; set; }
        public int UserId { get; set; }
        public string Status { get; set; }

        public virtual Room Room { get; set; }
        public virtual User User { get; set; }
    }
}