CREATE TABLE [dbo].[User]
(
	UserId INT NOT NULL PRIMARY KEY IDENTITY,	
	[Password] VARCHAR(255) NOT NULL,
	FirstName VARCHAR(255) NOT NULL,
	LastName VARCHAR(255) NOT NULL,
	Email VARCHAR(255) NOT NULL,
	[Address] VARCHAR(255) NOT NULL,
	DateOfBirth DATETIMEOFFSET,
	Sex INT NOT NULL
)
